### PR TITLE
update to 8.5.0, remove svg to png gulp-raster

### PR DESCRIPTION
**Pull request by jdonisvitch**

### CODE REVIEW

**Comment by mattboutet** [comment]
I don't bootstrap, so forgive my newb-ness: Should we be concerned about including an alpha version in this project?  Building on top of an alpha release _feels_ wrong to me, but maybe it's cool in Front-end land?

**Comment by devinivy** [comment]
☝️ Valid thing to consider.  It sucks to be caught in between versions (esp. with a major rewrite, as in bootstrap's case), so I understand the tendency to get ahead of things by pulling in an alpha.  On that note, v4-alpha5 is _already out_ so we really oughtta proceed with caution :P

**Comment by jdonisvitch** [comment]
Totally agree! I was just making a PR on this fork to match/bring it up to speed on sage's major release 8.5.0. Which adopted the alpha 🎱. Bootstrap is a special case as well, I am not actually planning on merging this into any project that we've started but I'm starting a project that is very mobile/tablet heavy and I hope to adopt a nicer BS4 solution with it.

**Comment by jdonisvitch** [comment]
Ohh and another thing. I freaking hated how it used bootstrap sass before, this pulls directly from bootstraps repo now and removes abunch of ugly overrides and processing.

**Pull request closed without merging**
